version: '3.7'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - shiny-monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  shiny-monitoring:

volumes:
  grafana-data:
